# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KCsQ_SV896Pzu70aAUQMtFGWWztK5LeD
"""

# STEP 1. IMPORT LIBRARIES

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="darkgrid")

# STEP 2. UPLOADING DATASET
from google.colab import files
uploaded = files.upload()
df = pd.read_csv(next(iter(uploaded)))
print("First 5 rows:")
print(df.head())

# STEP 3. DATASET STRUCTURE
print("\nDataset Info:")
print(df.info())
print("\nStatistical Summary:")
print(df.describe(include='all'))
print("\nUnique Values:")
for col in df.columns:
    print(col, ":", df[col].nunique())

# STEP 4. DATA QUALITY CHECKS

# Missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Duplicates
print("\nDuplicate Rows:", df.duplicated().sum())

# Invalid Ages
if 'Age' in df.columns:
    invalid_age = df[(df['Age'] < 0) | (df['Age'] > 120)]
    print("\nInvalid Age Rows:")
    print(invalid_age)

# Category inconsistencies
for col in ['Gender', 'TriageLevel', 'AdmissionStatus']:
    if col in df.columns:
        print(f"\nUnique values in {col}:")
        print(df[col].unique())

# STEP 5. DATA CLEANING

# Handle missing values
if 'Age' in df.columns:
    df['Age'].fillna(df['Age'].median(), inplace=True)

if 'WaitingTimeMinutes' in df.columns:
    df['WaitingTimeMinutes'].fillna(df['WaitingTimeMinutes'].median(), inplace=True)

# Remove duplicates
df.drop_duplicates(inplace=True)

# Fix invalid ages
if 'Age' in df.columns:
    df = df[(df['Age'] >= 0) & (df['Age'] <= 120)]

# Standardize categories
for col in ['Gender', 'AdmissionStatus', 'TriageLevel']:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip().str.capitalize()

# STEP 6. OUTLIER REMOVAL (IQR)
if 'WaitingTimeMinutes' in df.columns:
    Q1 = df['WaitingTimeMinutes'].quantile(0.25)
    Q3 = df['WaitingTimeMinutes'].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df = df[(df['WaitingTimeMinutes'] >= lower) &
            (df['WaitingTimeMinutes'] <= upper)]

print("\nData cleaned successfully!")

# STEP 7. UNIVARIATE ANALYSIS FOR WaitingTimeMinutes
plt.figure()
sns.histplot(df['WaitingTimeMinutes'], bins=20, kde=True)
plt.title("Distribution of Waiting Time")
plt.xlabel("Minutes")
plt.ylabel("Frequency")
plt.show()

# STEP 8. BIVARIATE ANALYSIS

# Waiting Time vs Triage Level
if 'TriageLevel' in df.columns:
    plt.figure()
    sns.boxplot(x='TriageLevel', y='WaitingTimeMinutes', data=df)
    plt.title("Waiting Time vs Triage Level")
    plt.show()

# Waiting Time vs Admission Status
if 'AdmissionStatus' in df.columns:
    plt.figure()
    sns.boxplot(x='AdmissionStatus', y='WaitingTimeMinutes', data=df)
    plt.title("Waiting Time vs Admission Status")
    plt.show()

# STEP 9. FINAL CLEAN DATA
print("\nFinal Cleaned Data:")
print(df.head())

# STEP 1. IMPORT LIBRARIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="darkgrid")

# STEP 2. UPLOAD DATASET
from google.colab import files
uploaded = files.upload()
df = pd.read_csv(next(iter(uploaded)))
print("Preview:")
print(df.head())

# STEP 3. DATASET STRUCTURE

print("\nDataset Info:")
df.info()

print("\nSummary:")
print(df.describe(include='all'))

# STEP 4. DATA QUALITY SUMMARY TABLE
quality_report = pd.DataFrame({
    "Column": df.columns,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique().values,
    "Data Type": df.dtypes.values
})
print("\nData Quality Report:")
print(quality_report)

# STEP 5. DETECT ISSUES
# Duplicates
print("\nDuplicate Rows:", df.duplicated().sum())

# Invalid discount (>100 or <0)
if 'DiscountPercent' in df.columns:
    print("\nInvalid Discounts:")
    print(df[(df['DiscountPercent'] < 0) | (df['DiscountPercent'] > 100)])

# Category inconsistencies
for col in ['Returned', 'PaymentMethod', 'ProductCategory', 'CustomerRegion']:
    if col in df.columns:
        print(f"\nUnique values in {col}:")
        print(df[col].unique())

# STEP 6. DATA CLEANING
# Fill missing values
for col in df.select_dtypes(include=np.number).columns:
    df[col].fillna(df[col].median(), inplace=True)

for col in df.select_dtypes(include='object').columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

# Remove duplicates
df.drop_duplicates(inplace=True)

# Fix discount values
if 'DiscountPercent' in df.columns:
    df = df[(df['DiscountPercent'] >= 0) & (df['DiscountPercent'] <= 100)]

# Standardize categorical values
for col in ['Returned', 'PaymentMethod', 'ProductCategory', 'CustomerRegion']:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip().str.capitalize()

print("\nData cleaned!")

# STEP 7. FREQUENCY TABLE (Returned)
freq_table = df['Returned'].value_counts()
print("\nReturned Frequency Table:")
print(freq_table)

# Bar Chart
plt.figure()
freq_table.plot(kind='bar')
plt.title("Return Status Distribution")
plt.xlabel("Returned")
plt.ylabel("Count")
plt.show()

# STEP 8. BOXPLOT (Order Value vs Returned)
plt.figure()
sns.boxplot(x='Returned', y='OrderValue', data=df)
plt.title("Order Value vs Returned")
plt.show()

# STEP 9. DELIVERY DAYS ANALYSIS
plt.figure()
sns.boxplot(x='Returned', y='DeliveryDays', data=df)
plt.title("Delivery Days vs Returned")
plt.show()

# STEP 10. CORRELATION HEATMAP
plt.figure()
numeric_df = df.select_dtypes(include=np.number)
sns.heatmap(numeric_df.corr(), annot=True)
plt.title("Correlation Heatmap")
plt.show()

# STEP 11. FINAL CLEAN DATA
print("\nFinal Data Preview:")
print(df.head())

# STEP 1. IMPORT LIBRARIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="darkgrid")

# STEP 2. UPLOAD DATASET
from google.colab import files
uploaded = files.upload()
df = pd.read_csv(next(iter(uploaded)))
print("Preview:")
print(df.head())

# STEP 3. DATASET STRUCTURE
print("\nDataset Info:")
df.info()
print("\nSummary:")
print(df.describe(include='all'))

# Identify variable types
print("\nColumn Types:")
for col in df.columns:
    if df[col].dtype == 'object':
        print(col, "-> Categorical/ID")
    else:
        print(col, "-> Numerical")

# STEP 4. DATA QUALITY ISSUES
# Missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Duplicates
print("\nDuplicate Rows:", df.duplicated().sum())

# Invalid Attendance (>100)
if 'AttendancePercent' in df.columns:
    print("\nInvalid Attendance:")
    print(df[df['AttendancePercent'] > 100])

# Extreme Income (check outliers)
if 'FamilyIncome' in df.columns:
    sns.boxplot(x=df['FamilyIncome'])
    plt.title("Family Income Outliers")
    plt.show()

# Category inconsistencies
for col in ['Department', 'DropoutRisk', 'ScholarshipStatus']:
    if col in df.columns:
        print(f"\nUnique values in {col}:")
        print(df[col].unique())

# STEP 5. DATA CLEANING
# Fill missing values
for col in df.select_dtypes(include=np.number).columns:
    df[col].fillna(df[col].median(), inplace=True)

for col in df.select_dtypes(include='object').columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

# Remove duplicates
df.drop_duplicates(inplace=True)

# Fix attendance (>100)
if 'AttendancePercent' in df.columns:
    df = df[df['AttendancePercent'] <= 100]

# Standardize categories
for col in ['Department', 'DropoutRisk', 'ScholarshipStatus']:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip().str.capitalize()

# Remove extreme income outliers (IQR)
if 'FamilyIncome' in df.columns:
    Q1 = df['FamilyIncome'].quantile(0.25)
    Q3 = df['FamilyIncome'].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df = df[(df['FamilyIncome'] >= lower) & (df['FamilyIncome'] <= upper)]

print("\nData cleaned!")

# STEP 6. DISTRIBUTION PLOT (Attendance)
plt.figure()
sns.histplot(df['AttendancePercent'], bins=20, kde=True)
plt.title("Attendance Distribution")
plt.xlabel("Attendance %")
plt.show()

# STEP 7. SCATTER PLOT (LMS vs Assignment)
plt.figure()
sns.scatterplot(x='LMSLoginsPerWeek', y='AssignmentAverage', hue='DropoutRisk', data=df)
plt.title("LMS Logins vs Assignment Average")
plt.show()

# STEP 8. BOX PLOT (Assignment vs DropoutRisk)
plt.figure()
sns.boxplot(x='DropoutRisk', y='AssignmentAverage', data=df)
plt.title("Assignment Average vs Dropout Risk")
plt.show()

# STEP 9. CROSS TAB (Scholarship vs Dropout)
crosstab = pd.crosstab(df['ScholarshipStatus'], df['DropoutRisk'])
print("\nCrosstab:")
print(crosstab)
crosstab.plot(kind='bar')
plt.title("Scholarship vs Dropout Risk")
plt.show()

# STEP 10. FINAL DATA
print("\nFinal Data Preview:")
print(df.head())